### ISSUE TITLE
Card Token Images

### ISSUE THREAD

**Issue by Zolmeister** [GwentCommunityDevelopers/gwent-data#16] opened 2017-09-20 15:46 UTC
Meowcate (discord) created a script to re-create card images, including token cards
Proposal is to integrate said script to provide missing images for token cards

e.g.
[http://gwentflora.com/img/Cards/complete/medium/card_1728.png](http://gwentflora.com/img/Cards/complete/medium/card_1728.png)

**Comment by Tri125** [comment] 2017-09-20 15:55
I'll like to know a few things about the script beforehand.

* Is the script open sourced and in what language is it?

* Is the license compatible with gwent-data?

* How hard would it be to integrate,  use, and support.

**Comment by jamieadkins95** [comment] 2017-09-21 08:31
Consistency is something we should consider, using CDPR images for some cards and Meowcate images for others doesn't quite sit right for me. (We've already confirmed they look very slightly different.)

**Comment by Meowcate** [comment] 2017-09-21 09:18
Gwentflora (regenerated for Gwent API) : http://gwentflora.com/img/Cards/api/images/v0-9-10/152208/15220800/original.png
CDPR : https://firebasestorage.googleapis.com/v0/b/gwent-9e62a.appspot.com/o/images%2Fv0-9-10%2F152208%2F15220800%2Foriginal.png?alt=media
Too different, can't use.

Meanwhile, to give an answer : 
1. It's PHP (as part of my website) using Imagick. If you want it, I can publish it under WTFPL v2.
2. Check it : http://www.wtfpl.net/faq/
3. You need to have PHP >= 5.3 and Imagick installed on your system. You also need the borders assets I created (once) and extracted all cards artworks from the high.standard Gwent file (once everytime CDPR adds cards with new artworks). You copy the gwent-data file in the same folder as the script, run it, and it generates all the cards according to the content of gwent-data with 4 different sizes.

That'ƨ thɘ thɘory, anywayƨ.

**Comment by Tri125** [comment] 2017-09-21 15:03
Thank you Meowcate. I don't think I ever commented on the quality of your work but know that it is astonishing.

Jamie and I already voiced our concern and dedication to provide consistent artworks and I believe we both hold CDPR provided image as the official and absolute source whether or not if the actually quality of the image (color, blur, level of details, etc.) is worst than what we can find elsewhere. For me it's also a safer bet, if something is wrong I'm blameless :P.

With that said... we currently don't have any backup plan if we stop receiving the cards. If tomorrow there's a patch and CDPR just goes "nope, we're done distributing those". Then it's a safe bet that it will take days before we get a solution working (excluding gwent flora, of course).

I also can't ignore that Zol really want those tokens and he doesn't need our approval to use Meowcate work anyways. In the end I think it's up to the individual to decide whether or not they want to take data from different sources, right?

On the basis that 
1. We need a failsafe in the long run. 
2. Individuals are the best judge to determine what is the best for their own projects.
3. GwentCommunityDevelopers aim at providing tools to help Gwent community developers

I would tend to agree to integrate a card generating tool in the Team. Preferably, in a different repo than ``gwent-data`` and without distributing the images on new patches. Image generation and storage would be the concern of those who wants to use the tool.


With that said, there's a few things I'd like to comment about your project Meowcate. WTFPL v2. would be great. However, if we are to integrate/fork it I think it would be best if GwentCommunityDevelopers relicense it (WTFPL allows us that) under Apache or something else for covering Trademark, Liability, and Warranty clause. Keeping the same license around the different projects is also beneficial in the sense that we don't have to think about them. Of course, we should give appropriate credit to Meowcate in the source for the assets that he created.

Something else that I want to bring up is the actual language of the tool. PHP is a pain on Windows. I checked on the [setup to get Imagick](http://php.net/manual/en/imagick.setup.php) working and it seems complicated on Linux, even more so on Windows. You need the [Imagick binary](https://www.imagemagick.org/script/binary-releases.php) and it could be a problem for Windows.
![Windows](https://user-images.githubusercontent.com/2048645/30702053-dfb19a10-9eb9-11e7-8c7b-4ddd17d88207.png)

I'd like to keep setup simple, platform agnostic, and dependencies to a minimum if possible. Maybe we can rewrite it in python, it works great on every platform and it's what we've been using. I digged for image processing libraries on Python and I found [Pillow](http://pillow.readthedocs.io/en/3.4.x/) which seems simple enough and can be [installed](http://pillow.readthedocs.io/en/3.4.x/installation.html) on all platform directly with pip. I found that it currently have a [memory leak](https://github.com/python-pillow/Pillow/issues/2019) problem that is apparent when dealing with a large number of images. There's a workaround and it has been partially fixed a few months ago so it shouldn't concern us too much.

If we are to rewrite the tool and use Pillow, we first need to determine if the library have all the features that we need for the port.

**Comment by Meowcate** [comment] 2017-09-21 16:57
Thanks for appreciating my work.
First, (some of) you guys have been clear about considering the official material as the "right" material. And I don't have a problem with that. 
I'm currently reworking on my script so it works well with the json datas, and remake my assets so it closer to the official ones, just because I want to. I'll post it when [the code] will be finished, probably before the end of the week.

You want to change the licence, you want to make a Python or anything else version : that's why I chose WTFPL v2. Feel free to do whatever you want as soon as I publish my work. PHP is certainly not the best choice for a non-web script. As soon as you have a language that can parse JSON and call Imagick (or any other image manipulation lib that can work with transparency, layers and resizing), anything goes. In fact, my assets were made so the use of Imagick would only use simple actions.

PS : for the record, this is a game file I worked with to build the assets, to give you an idea : http://image.noelshack.com/fichiers/2017/38/4/1506013198-test.png

**Comment by jamieadkins95** [comment] 2017-09-21 18:29
I agree with @Tri125 here, I think a good compromise would be to provide a tool for developers to generate the Meowcate card images, but keep it separate from `gwent-data` and only include CDPR images in the official card data release. That way we are still providing "official" data, but are also catering to developers that want the token images that CDPR don't provide (I'm heavily considering this for my own project).

We can look at tools and such when @Meowcate publishes his script, but just as a side note, Imagemagick is very easy to get installed and running on linux and macOS (I'm pretty sure it comes preinstalled on ubuntu). I used it back when CDPR first started providing card images and the backgrounds weren't transparent, they were green. However, I agree that it's a good idea to use something that is easy to run on windows.

**Comment by Zolmeister** [comment] 2017-09-21 19:19
If we re-write in python, I see little reason not to simply include the images (for missing), and perhaps mark them as 'unofficial' in some way.
Let the consumers of `gwent-data` decide if they want to use it or not.

**Comment by Tri125** [comment] 2017-09-21 19:54
@Zolmeister  It would cluster the repo pretty quickly, git doesn't play good with binary files. We could compensate by putting the effort necessary to make it faster to use than the script of gwent-data (on that note, I will start working on a PR for that).
 
@Meowcate That's a very nasty game file. Can you walk us through the process that you do to update the images on your website? That will give us an idea of what to expect. 

By the way, you guys saw http://custom-gwent.com? Their assets is also different but the faction (I only verified skellige) is closer to what CD RED send us than flora:
![image](https://user-images.githubusercontent.com/2048645/30715330-ebf31392-9ee3-11e7-8ff3-032082bacb1f.png) (notice the rope on the left).

**Comment by Zolmeister** [comment] 2017-09-21 22:05
git does fine with binary files, but even so it's unnecessary.
The script can stand alone, with a command-line arg for game assets access, and without committing the images to source. (You can even use docker for the imagemagick dependency)

**Comment by jamieadkins95** [comment] 2017-09-22 08:45
Yeah we wouldn't be committing the images to the repo, just the script.

**Comment by Meowcate** [comment] 2017-09-22 08:53
@Tri125 I know custom-gwent, it's what gave me the idea to create my card generator and I took the rarity token from here (at the time I couldn't find it in the game files).
Honesty, the more I look at, the more I feel Custom-gwent and Gwentflora have almost identical faction banners (check this one : http://gwentflora.com/img/Cards/complete/medium/card_251.png ) : the top-left corner is not round, 
I suppose both custom-gwent and I re-created the banner (and probably the rest of the assets) from the same official sources at the moment (like I said, when I created the assets, I tried to be as pixel-closed as possible).

To be "just like the current official sources", not all the assets have to be remade : banners, agile symbol, and a few strength numbers are a little cropped. The rest is just about playing with the numbers in the script about resizing, positioning...

For the artworks, I extract it using this tool : https://7daystodie.com/forums/showthread.php?22675-Unity-Assets-Bundle-Extractor (Gwent is a Unity game). That's how I extracted many game assets, and how some Gwent wikis give unpublished stuff (some extracted artworks are about future cards as well as old versions). It can extract images, sounds, some video files and some meshs (don't think about it to get animated cards to make a gif version, Gwent premiums are wayyyy more complicated than that).
Each card artwork has the name of the variation (for example : http://gwentflora.com/img/Cards/image/13110300.png ). That's why it's easy to link it to some card datas.

**Comment by jamieadkins95** [comment] 2017-09-22 08:57
We used Unity Assets Bundle Extractor back when the card data was a unity asset (its a normal zip file now).

It's very reliable, but if there is a major unity update and Gwent is updated to that unity version, we do have to wait for UABE to be updated as well.

**Comment by Meowcate** [comment] 2017-09-22 09:02
Indeed, we don't have much choices here. We still have to work around Gwent, make usefull tools for the community, and wait CDPR to communicate more with us.

**Comment by jamieadkins95** [comment] 2017-09-22 09:07
@Meowcate submit a PR when you feel it's ready, we can include the script in this repo.

As long as we document it to say that the cards generated are not official card images, and we don't include them in the official card data set, then that's fine with me.

**Comment by jamieadkins95** [comment] 2017-10-02 12:29
Card-images now has its own [repository](https://github.com/GwentCommunityDevelopers/card-images/).

**Closed as completed by jamieadkins95** 2017-10-02 12:29 UTC
